### PR TITLE
match ch. 2 FROM image to other labs

### PR DESCRIPTION
**Pull request by tchughesiv**

### CODE REVIEW

**Comment by dustymabe** [comment]
pretty sure we were trying to do this on purpose to make a point. 

```
>>> No tags on image specification - updates could break things
```

although `registry.access.redhat.com/rhel7` isn't really a "tag"

**Comment by tchughesiv** [comment]
hmm, ya... a tag in the context of "best practice" would probably be something like:
```registry.access.redhat.com/rhel7:7.3-74```

Using _registry.access.redhat.com/rhel_ in ch. 2 but not in the others doesn't make sense, imo...
BUT, if we wanted to use it in chapter 2, we'll likely need to make a point to cache _registry.access.redhat.com/rhel_ ... even if its just a pointer to _registry.access.redhat.com/rhel7_

**Comment by dustymabe** [comment]
> hmm, ya... a tag in the context of "best practice" would probably be something like:
> registry.access.redhat.com/rhel7:7.3-74
> 

agreed. if that is the current latest version I can add that to the list of images to pre-cache

> Using registry.access.redhat.com/rhel in ch. 2 but not in the others doesn't make sense, imo...
> BUT, if we wanted to use it in chapter 2, we'll likely need to make a point to cache registry.access.redhat.com/rhel ... even if its just a pointer to registry.access.redhat.com/rhel7

I already pre-cache `rhel`, but like I said if we want to use "real tags rather than fake ones, i'm ok with that.

**Comment by tchughesiv** [comment]
ok... my vote would be, at the very least, to use "FROM registry.access.redhat.com/rhel**7**" in all chapters for consistency.
For ch. 3, if we wanted, we could add the 7.3-74 tag as well to demonstrate a good practice.

Thoughts?

**Comment by dustymabe** [comment]
my thoughts are that we use `rhel7` up until the point where we explain that tagging is better and then we use `registry.access.redhat.com/rhel7:7.3-74` at every point after that.

**Pull request merged**
