### PR TITLE
remove ch. 1 root requirement

### LINKED ISSUE #47: ch. 1 - root not necessary
This line unecessary:
_Perform the following commands as root unless instructed otherwise._
https://github.com/dustymabe/summit-2017-container-lab/blob/691f87bd5352242b71dda49723ca971bed1d0ac1/labs/lab1/chapter1.md

Root is not required and, if anything, causes issues w/ the lab.  The docker client can't connect as root.

Sudo also shouldn't be necessary, but maybe makes sense left in?
```sudo systemctl status docker```

### PR DESCRIPTION
**Pull request by tchughesiv**
fix https://github.com/dustymabe/summit-2017-container-lab/issues/47

### CODE REVIEW

**Comment by dustymabe** [comment]
are there any other labs that need this same cleanup? Should we actually instruct the user to execute the statements as `student` instead?

**Comment by tchughesiv** [comment]
> are there any other labs that need this same cleanup?

I don't believe so.

> Should we actually instruct the user to execute the statements as student instead?

we could, sure... maybe change the line instead of delete?

**Comment by dustymabe** [comment]
works for me

**Comment by dustymabe** [comment]
should the move to lowercase labels be in this PR? seems like a separate one to me

**Pull request closed without merging**
